name: Setup ONNX Runtime
description: Download and stage ONNX Runtime libraries for bindings
inputs:
  ort-version:
    description: ONNX Runtime version to download
    required: true
  dest-dir:
    description: Directory (relative to workspace) where libraries should be copied
    required: false
    default: crates/kreuzberg-node
  arch-id:
    description: Override architecture (x64|arm64). Defaults to runner architecture.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Cache ONNX Runtime
      id: cache-onnx
      uses: actions/cache@v5
      with:
        path: |
          ${{ runner.temp }}/onnxruntime
        key: onnx-v2-${{ runner.os }}-${{ inputs.arch-id != '' && inputs.arch-id || runner.arch }}-${{ inputs.ort-version }}

    - name: Prepare ONNX Runtime (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euo pipefail
        ort_version="${{ inputs.ort-version }}"
        extract_dir="$RUNNER_TEMP/onnxruntime"

        arch_id="${{ inputs.arch-id }}"
        if [ -z "$arch_id" ]; then
          case "$(uname -m)" in
            x86_64|amd64) arch_id="x64" ;;
            arm64|aarch64) arch_id="arm64" ;;
            *) echo "Unsupported Linux architecture: $(uname -m)" >&2; exit 1 ;;
          esac
        fi

        case "$arch_id" in
          x64)
            ort_dir_name="onnxruntime-linux-x64-${ort_version}"
            archive="onnxruntime-linux-x64-${ort_version}.tgz"
            ;;
          arm64)
            ort_dir_name="onnxruntime-linux-aarch64-${ort_version}"
            archive="onnxruntime-linux-aarch64-${ort_version}.tgz"
            ;;
          *)
            echo "Unsupported Linux arch-id: $arch_id" >&2
            exit 1
            ;;
        esac

        # Download only if not cached
        if [ ! -d "$extract_dir/$ort_dir_name" ]; then
          echo "Cache miss: Downloading ONNX Runtime ${ort_version}"
          curl -fsSL --retry 5 --retry-delay 5 --retry-all-errors -o "$RUNNER_TEMP/$archive" "https://github.com/microsoft/onnxruntime/releases/download/v${ort_version}/$archive"
          mkdir -p "$extract_dir"
          tar -xzf "$RUNNER_TEMP/$archive" -C "$extract_dir"
        else
          echo "Cache hit: Using cached ONNX Runtime ${ort_version}"
        fi
        ort_root="$extract_dir/$ort_dir_name"

        # Verify library directory exists and contains libraries
        if [ ! -d "$ort_root/lib" ]; then
          echo "ERROR: ONNX Runtime lib directory missing at $ort_root/lib" >&2
          echo "Available directories:" >&2
          ls -la "$extract_dir" >&2 || true
          exit 1
        fi

        # Verify that library files actually exist
        if ! ls "$ort_root/lib"/*.so* 1> /dev/null 2>&1; then
          echo "ERROR: No ONNX Runtime libraries found in $ort_root/lib" >&2
          echo "Directory contents:" >&2
          ls -la "$ort_root/lib" >&2 || true
          exit 1
        fi

        dest="$GITHUB_WORKSPACE/${{ inputs.dest-dir }}"
        mkdir -p "$dest"
        cp -f "$ort_root/lib/"*.so* "$dest/"

        # Append to existing RUSTFLAGS if present
        if [ -n "${RUSTFLAGS:-}" ]; then
          rustflags="$RUSTFLAGS -L $ort_root/lib"
        else
          rustflags="-L $ort_root/lib"
        fi

        # Add library path variables and RUSTFLAGS for complete library path resolution
        {
          echo "ORT_LIB_LOCATION=$ort_root/lib"
          echo "ORT_PREFER_DYNAMIC_LINK=1"
          echo "ORT_SKIP_DOWNLOAD=1"
          echo "ORT_STRATEGY=system"
          echo "LD_LIBRARY_PATH=$ort_root/lib:$dest:${LD_LIBRARY_PATH:-}"
          echo "LIBRARY_PATH=$ort_root/lib:$dest:${LIBRARY_PATH:-}"
          echo "RUSTFLAGS=$rustflags"
        } >> "$GITHUB_ENV"

    - name: Prepare ONNX Runtime (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -euo pipefail
        ort_version="${{ inputs.ort-version }}"
        extract_dir="$RUNNER_TEMP/onnxruntime"

        arch_id="${{ inputs.arch-id }}"
        if [ -z "$arch_id" ]; then
          arch="$(uname -m)"
          if [ "$arch" = "arm64" ]; then
            arch_id="arm64"
          else
            arch_id="x64"
          fi
        fi

        case "$arch_id" in
          arm64) ort_arch="arm64" ;;
          x64) ort_arch="x86_64" ;;
          *) echo "Unsupported macOS arch-id: $arch_id" >&2; exit 1 ;;
        esac
        echo "Using macOS ONNX Runtime arch: $ort_arch"

        # Download only if not cached
        if [ ! -d "$extract_dir/onnxruntime-osx-${ort_arch}-${ort_version}" ]; then
          echo "Cache miss: Downloading ONNX Runtime ${ort_version} for macOS ${ort_arch}"
          archive="onnxruntime-osx-${ort_arch}-${ort_version}.tgz"
          curl -fsSL --retry 5 --retry-delay 5 --retry-all-errors -o "$RUNNER_TEMP/$archive" "https://github.com/microsoft/onnxruntime/releases/download/v${ort_version}/$archive"
          mkdir -p "$extract_dir"
          tar -xzf "$RUNNER_TEMP/$archive" -C "$extract_dir"
        else
          echo "Cache hit: Using cached ONNX Runtime ${ort_version}"
        fi
        ort_root="$extract_dir/onnxruntime-osx-${ort_arch}-${ort_version}"

        # Verify library directory exists and contains libraries
        if [ ! -d "$ort_root/lib" ]; then
          echo "ERROR: ONNX Runtime lib directory missing at $ort_root/lib" >&2
          echo "Available directories:" >&2
          ls -la "$extract_dir" >&2 || true
          exit 1
        fi

        # Verify that library files actually exist
        if ! ls "$ort_root/lib"/libonnxruntime*.dylib 1> /dev/null 2>&1; then
          echo "ERROR: No ONNX Runtime libraries found in $ort_root/lib" >&2
          echo "Directory contents:" >&2
          ls -la "$ort_root/lib" >&2 || true
          exit 1
        fi

        dest="$GITHUB_WORKSPACE/${{ inputs.dest-dir }}"
        mkdir -p "$dest"
        cp -f "$ort_root/lib/"libonnxruntime*.dylib "$dest/"

        # Append to existing RUSTFLAGS if present
        if [ -n "${RUSTFLAGS:-}" ]; then
          rustflags="$RUSTFLAGS -L $ort_root/lib"
        else
          rustflags="-L $ort_root/lib"
        fi

        # Add both DYLD environment variables and RUSTFLAGS for complete library path resolution
        {
          echo "ORT_LIB_LOCATION=$ort_root/lib"
          echo "ORT_PREFER_DYNAMIC_LINK=1"
          echo "ORT_SKIP_DOWNLOAD=1"
          echo "ORT_STRATEGY=system"
          echo "DYLD_LIBRARY_PATH=$ort_root/lib:$dest:${DYLD_LIBRARY_PATH:-}"
          echo "DYLD_FALLBACK_LIBRARY_PATH=$ort_root/lib:$dest:${DYLD_FALLBACK_LIBRARY_PATH:-}"
          echo "LIBRARY_PATH=$ort_root/lib:$dest:${LIBRARY_PATH:-}"
          echo "RUSTFLAGS=$rustflags"
        } >> "$GITHUB_ENV"

    - name: Prepare ONNX Runtime (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $OrtVersion = "${{ inputs.ort-version }}"
        $ExtractRoot = Join-Path $env:TEMP "onnxruntime"
        $ArchId = "${{ inputs.arch-id }}"
        if ([string]::IsNullOrWhiteSpace($ArchId)) {
          $ArchId = "x64"
        }

        $OrtRoot = Join-Path $ExtractRoot "onnxruntime-win-$ArchId-$OrtVersion"
        $OrtBin = Join-Path $OrtRoot 'bin'
        $OrtLib = Join-Path $OrtRoot 'lib'

        # Download only if not cached
        if (-Not (Test-Path $OrtRoot)) {
          Write-Host "Cache miss: Downloading ONNX Runtime $OrtVersion"
          $Archive = "onnxruntime-win-$ArchId-$OrtVersion.zip"
          $DownloadPath = Join-Path $env:TEMP $Archive
          Invoke-WebRequest -Uri "https://github.com/microsoft/onnxruntime/releases/download/v$OrtVersion/$Archive" -OutFile $DownloadPath -UseBasicParsing -MaximumRetryCount 5 -RetryIntervalSec 5
          New-Item -ItemType Directory -Path $ExtractRoot -Force | Out-Null
          Expand-Archive -Path $DownloadPath -DestinationPath $ExtractRoot -Force
        } else {
          Write-Host "Cache hit: Using cached ONNX Runtime $OrtVersion"
        }

        # Verify library directory exists
        if (!(Test-Path (Join-Path $OrtRoot 'lib'))) {
          Write-Error "ERROR: ONNX Runtime lib directory missing at $OrtRoot\lib"
          Get-ChildItem -Path $ExtractRoot -Recurse | Write-Host
          exit 1
        }

        # Verify that library files actually exist
        $LibFiles = Get-ChildItem -Path $OrtLib -Filter "*.lib" -ErrorAction SilentlyContinue
        if ($LibFiles.Count -eq 0) {
          Write-Error "ERROR: No ONNX Runtime library files found in $OrtRoot\lib"
          Get-ChildItem -Path $OrtLib | Write-Host
          exit 1
        }

        # Locate runtime DLLs (recent releases place them under lib/ instead of bin/)
        $RuntimeDirs = @()
        if (Test-Path $OrtBin) { $RuntimeDirs += $OrtBin }
        if (Test-Path $OrtLib) { $RuntimeDirs += $OrtLib }
        $RuntimeDirs += $OrtRoot

        $DllFiles = @()
        foreach ($dir in $RuntimeDirs) {
          $DllFiles += Get-ChildItem -Path $dir -Filter "*.dll" -ErrorAction SilentlyContinue
        }
        if ($DllFiles.Count -eq 0) {
          $DllFiles = Get-ChildItem -Path $OrtRoot -Recurse -Filter "*.dll" -ErrorAction SilentlyContinue
        }
        if ($DllFiles.Count -eq 0) {
          Write-Error "ERROR: No ONNX Runtime runtime DLLs found under $OrtRoot"
          Get-ChildItem -Path $OrtRoot -Recurse | Write-Host
          exit 1
        }
        $DllDirs = $DllFiles | Select-Object -ExpandProperty DirectoryName -Unique
        $DllPathPrefix = ($DllDirs -join ';')

        $Dest = Join-Path $env:GITHUB_WORKSPACE "${{ inputs.dest-dir }}"
        New-Item -ItemType Directory -Path $Dest -Force | Out-Null
        Copy-Item -Path (Join-Path $OrtRoot 'lib' '*') -Destination $Dest -Force
        foreach ($dir in $DllDirs) {
          Copy-Item -Path (Join-Path $dir '*.dll') -Destination $Dest -Force
        }

        # Append to existing RUSTFLAGS if present
        $RustFlags = if ($env:RUSTFLAGS) { "$env:RUSTFLAGS -L $OrtRoot\lib" } else { "-L $OrtRoot\lib" }

        @(
          "ORT_LIB_LOCATION=$OrtRoot\lib"
          "ORT_PREFER_DYNAMIC_LINK=1"
          "ORT_SKIP_DOWNLOAD=1"
          "ORT_STRATEGY=system"
          "RUSTFLAGS=$RustFlags"
          "LIB=$OrtRoot\lib;$env:LIB"
          "LIBRARY_PATH=$OrtRoot\lib;$env:LIBRARY_PATH"
          "PATH=$DllPathPrefix;$Dest;$env:PATH"
        ) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
