name: Setup OpenSSL
description: Install and expose OpenSSL headers/libs across platforms
runs:
  using: composite
  steps:
    - name: Restore OpenSSL cache (Linux)
      if: runner.os == 'Linux'
      uses: actions/cache@v5
      id: cache-linux
      with:
        path: |
          /home/runner/.cache/openssl-build
        key: openssl-${{ runner.os }}-${{ runner.arch }}-v2
        restore-keys: |
          openssl-${{ runner.os }}-

    - name: Install OpenSSL (Linux)
      if: runner.os == 'Linux' && steps.cache-linux.outputs.cache-hit != 'true'
      shell: bash
      run: scripts/ci/actions/setup-openssl/linux-install.sh

    - name: Configure OpenSSL environment (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: scripts/ci/actions/setup-openssl/linux-configure.sh

    - name: Restore OpenSSL cache (macOS)
      if: runner.os == 'macOS'
      uses: actions/cache@v5
      id: cache-macos
      with:
        path: /usr/local/opt/openssl@3/
        key: openssl-${{ runner.os }}-${{ runner.arch }}-v2
        restore-keys: |
          openssl-${{ runner.os }}-

    - name: Install OpenSSL (macOS)
      if: runner.os == 'macOS' && steps.cache-macos.outputs.cache-hit != 'true'
      shell: bash
      run: scripts/ci/actions/setup-openssl/macos-install.sh

    - name: Configure OpenSSL environment (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: scripts/ci/actions/setup-openssl/macos-configure.sh

    - name: Restore OpenSSL cache (Windows)
      if: runner.os == 'Windows'
      uses: actions/cache@v5
      id: cache-windows
      with:
        path: |
          C:\vcpkg\installed\x64-windows-static-md
          C:\vcpkg\downloads
        key: openssl-${{ runner.os }}-${{ hashFiles('C:\vcpkg\vcpkg.exe') }}-v3
        restore-keys: |
          openssl-${{ runner.os }}-

    - name: Install OpenSSL (Windows)
      if: runner.os == 'Windows' && steps.cache-windows.outputs.cache-hit != 'true'
      shell: pwsh
      run: scripts/ci/actions/setup-openssl/windows-install.ps1

    - name: Verify OpenSSL installation (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: scripts/ci/actions/setup-openssl/windows-verify.ps1

    - name: Configure OpenSSL environment (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: scripts/ci/actions/setup-openssl/windows-configure.ps1
