name: Smoke test Node.js package
description: Tests Node.js package installation and functionality

inputs:
  package-tarball:
    description: Path to the npm package tarball (.tgz file)
    required: false
    default: ""
  package-spec:
    description: Explicit Node package spec (file:... or tarball path). Overrides workspace/tarball resolution.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Smoke test Node.js package
      shell: bash
      env:
        KREUZBERG_NODE_PKG: ${{ github.workspace }}/packages/typescript
      run: |
        set -euo pipefail
        tmp=$(mktemp -d)
        cp -R e2e/smoke/node/. "$tmp"/
        pushd "$tmp" >/dev/null

        package_spec="${{ inputs.package-spec }}"
        artifact_tar="${{ inputs.package-tarball }}"

        # Prefer explicit spec env if provided
        if [[ -z "$package_spec" && -n "${KREUZBERG_NODE_SPEC:-}" ]]; then
          package_spec="${KREUZBERG_NODE_SPEC}"
        fi

        # Resolve tarball if given
        if [[ -z "$package_spec" && -n "$artifact_tar" ]]; then
          tarball="$artifact_tar"
          if [[ "$tarball" != /* ]]; then
            tarball="${GITHUB_WORKSPACE}/${artifact_tar}"
          fi
          if [[ ! -e "$tarball" ]]; then
            echo "Provided Node artifact not found: $tarball" >&2
            exit 1
          fi
          stage_dir="$tmp/node-artifact"
          mkdir -p "$stage_dir"
          case "$tarball" in
            *.tar.gz|*.tgz)
              tar -xzf "$tarball" -C "$stage_dir"
              ;;
            *)
              cp "$tarball" "$stage_dir"/
              ;;
          esac

          pkg_file=$(find "$stage_dir" -maxdepth 3 -name \"*.tgz\" -type f | head -n 1)
          if [[ -n \"$pkg_file\" ]]; then
            cp \"$pkg_file\" ./kreuzberg.tgz
            package_spec=\"file:./kreuzberg.tgz\"
          else
            search_root=\"$stage_dir\"
            if [[ -d \"$stage_dir/npm\" ]]; then
              search_root=\"$stage_dir/npm\"
            fi
            pkg_dir=$(find \"$search_root\" -mindepth 1 -maxdepth 1 -type d | head -n 1 || true)
            if [[ -z \"$pkg_dir\" || ! -f \"$pkg_dir/package.json\" ]]; then
              echo \"Unable to determine Node package directory inside $tarball\" >&2
              ls -R \"$stage_dir\" >&2 || true
              exit 1
            fi
            normalized_path=$(PKG_DIR=\"$pkg_dir\" node -e \"const path=require('path');process.stdout.write(path.resolve(process.env.PKG_DIR).replace(/\\\\\\\\/g,'/'))\")
            package_spec=\"file:${normalized_path}\"
          fi
        fi

        # Final fallback to workspace path only if nothing else provided
        if [[ -z \"$package_spec\" ]]; then
          workspacePath=\"${KREUZBERG_NODE_PKG:-}\"
          if [[ -z \"$workspacePath\" ]]; then
            echo \"Unable to determine Node package location (provide package-tarball or KREUZBERG_NODE_SPEC)\" >&2
            exit 1
          fi
          workspace_normalized=$(WORKSPACE_PATH=\"$workspacePath\" node -e \"const path=require('path');process.stdout.write(path.resolve(process.env.WORKSPACE_PATH).replace(/\\\\\\\\/g,'/'))\")
          echo \"Falling back to workspace Node package at $workspace_normalized\"
          package_spec=\"file:${workspace_normalized}\"
        fi

        export KREUZBERG_NODE_SPEC=\"$package_spec\"
        echo \"Using Node package spec: $KREUZBERG_NODE_SPEC\"

        node \"$GITHUB_WORKSPACE/.github/actions/smoke-node/update-package-spec.js\"
        rm -f pnpm-lock.yaml
        pnpm install --no-frozen-lockfile

        pnpm run check
        popd >/dev/null
        echo "✓ Node.js package smoke test passed"
