name: Cleanup Rust Cache
description: Remove large build artifacts to reduce cache size before saving
runs:
  using: composite
  steps:
    - name: Cleanup build artifacts
      shell: bash
      run: |
        # Remove large PDFium build artifacts (100+ MB each)
        rm -rf target/*/build/kreuzberg-*/out/pdfium 2>/dev/null || true

        # Remove large compiled libraries (>10MB each)
        find target -type f -name "*.rlib" -size +10M -exec rm -f {} \; 2>/dev/null || true
        find target -type f -name "*.so" -size +10M -exec rm -f {} \; 2>/dev/null || true
        find target -type f -name "*.dylib" -size +10M -exec rm -f {} \; 2>/dev/null || true
        find target -type f -name "*.dll" -size +10M -exec rm -f {} \; 2>/dev/null || true

        # Remove incremental compilation cache
        rm -rf target/*/incremental 2>/dev/null || true

        # Report final cache size
        du -sh target 2>/dev/null || echo "No target directory found"
        echo "Rust cache cleanup completed"
